package pl.gda.pg.eti.kernelhive.common.clusterService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "ClusterBean", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/")
@XmlSeeAlso({
	ObjectFactory.class
})
public interface ClusterBean {

	/**
	 *
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "reportOver", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.ReportOver")
	@ResponseWrapper(localName = "reportOverResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.ReportOverResponse")
	@Action(input = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/reportOverRequest", output = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/reportOverResponse")
	public void reportOver(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 *
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "reportProgress", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.ReportProgress")
	@ResponseWrapper(localName = "reportProgressResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.ReportProgressResponse")
	@Action(input = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/reportProgressRequest", output = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/reportProgressResponse")
	public void reportProgress(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 *
	 * @return returns pl.gda.pg.eti.kernelhive.common.clusterService.JobInfo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getJob", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.GetJob")
	@ResponseWrapper(localName = "getJobResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.GetJobResponse")
	@Action(input = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/getJobRequest", output = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/getJobResponse")
	public JobInfo getJob();

	/**
	 *
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "reportPreview", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.ReportPreview")
	@ResponseWrapper(localName = "reportPreviewResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.ReportPreviewResponse")
	@Action(input = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/reportPreviewRequest", output = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/reportPreviewResponse")
	public void reportPreview(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") byte[] arg1);

	/**
	 *
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "update", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.Update")
	@ResponseWrapper(localName = "updateResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clusterService.UpdateResponse")
	@Action(input = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/updateRequest", output = "http://engine.kernelhive.eti.pg.gda.pl/ClusterBean/updateResponse")
	public int update(
			@WebParam(name = "arg0", targetNamespace = "") Cluster arg0);
}
