#!/bin/bash

###
# Data and variables
CMDS=( gcc make cmake java ant )
TARGET="build"
if [ $# -gt 0 ]; then
	TARGET="$1"
fi

###
# Checks if commands given as parameters are available
function check_dependencies() {
	echo "Will now check for required tools"
	for CMD in $@
	do
		echo -ne " Checking for $CMD.. "
		command -v $CMD >/dev/null 2>&1
		if [ $? -gt 0 ]; then
			echo "FAILED"
			echo -e " Command $CMD is not available. Please make sure it is installed and available on the path."
			exit 1
		fi
		echo "OK"
	done
}

function build_kh() {
	check_dependencies gcc make cmake java ant
	echo "Will now build KernelHive modules"
}

function deploy_kh() {
	echo "Will now deploy KernelHive modules"
}

function clean_kh() {
	check_dependencies make ant
	echo "Will now clean build output"
}

function purge_kh() {
	echo "Will now remove all build output"
}

case "$TARGET" in
	"build") build_kh ;;
	"deploy") deploy_kh ;;
	"clean") clean_kh ;;
	"purge") purge_kh ;;
	*) echo "Unsupported target: $TARGET"
esac

