#!/bin/sh

NAME=hive-cluster
DESC="KernelHive cluster subsystem"
DAEMON=/usr/bin/jsvc
DAEMON_JAR=./dist/hive-cluster.jar
PIDFILE=/var/run/$NAME.pid
LOGFILE=hive-cluster.log
BOOTSTRAP_CLASS=pl.gda.pg.eti.kernelhive.cluster.HiveCluster

#JAVA_HOME=/usr/lib/jvm/java-6-openjdk-i386/
JAVA_HOME=/usr/lib/jvm/java-6-sun/

CLUSTER_HOSTNAME=127.0.0.1
ENGINE_HOSTNAME=hive-engine
#ARGS="$CLUSTER_HOSTNAME" "$ENGINE_HOSTNAME"

set -e

case "$1" in
    start)
        echo -n "Starting $DESC: "
	if sudo "$DAEMON" -home $JAVA_HOME -pidfile "$PIDFILE" -outfile "$LOGFILE" -errfile "$LOGFILE" -cp "./dist/hive-cluster" "$BOOTSTRAP_CLASS" "$CLUSTER_HOSTNAME" "$ENGINE_HOSTNAME"; then
        	echo "$NAME."
	else
                echo "(already running)."
                exit 1
        fi

        ;;
    stop)
        echo -n "Stopping $DESC: "
	sudo "$DAEMON" -stop -pidfile "$PIDFILE" -cp "$DAEMON_JAR" "$BOOTSTRAP_CLASS"
        echo "$NAME."
        ;;
    *)
        echo "Usage: $0 { start | stop }" >&2
        exit 1
        ;;
esac

exit 0
