
package pl.gda.pg.eti.kernelhive.common.clientService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClientBean", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientBean {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "runGraph", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.RunGraph")
    @ResponseWrapper(localName = "runGraphResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.RunGraphResponse")
    public void runGraph(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
