
package pl.gda.pg.eti.kernelhive.common.clientService;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClientBean", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientBean {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorkflowResults", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.GetWorkflowResults")
    @ResponseWrapper(localName = "getWorkflowResultsResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.GetWorkflowResultsResponse")
    public String getWorkflowResults(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.gda.pg.eti.kernelhive.common.clientService.ClusterInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "browseInfrastructure", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.BrowseInfrastructure")
    @ResponseWrapper(localName = "browseInfrastructureResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.BrowseInfrastructureResponse")
    public List<ClusterInfo> browseInfrastructure();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitWorkflow", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.SubmitWorkflow")
    @ResponseWrapper(localName = "submitWorkflowResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.SubmitWorkflowResponse")
    public Integer submitWorkflow(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.gda.pg.eti.kernelhive.common.clientService.WorkflowInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "browseWorkflows", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.BrowseWorkflows")
    @ResponseWrapper(localName = "browseWorkflowsResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.BrowseWorkflowsResponse")
    public List<WorkflowInfo> browseWorkflows();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "terminateWorkflow", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.TerminateWorkflow")
    @ResponseWrapper(localName = "terminateWorkflowResponse", targetNamespace = "http://engine.kernelhive.eti.pg.gda.pl/", className = "pl.gda.pg.eti.kernelhive.common.clientService.TerminateWorkflowResponse")
    public void terminateWorkflow(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
